name: MYCI
on:
  push:
    branches:
    - main
    paths:
    - src/*
jobs:
    check-links:
      runs-on: ubuntu-latest
      steps:  
      - uses: actions/checkout@v1 
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: echo ${{  secrets.MYSECRETS  }}
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test
      - run: echo 111