name: MYCI
on:
  push:
    branches:
      - test
    tags:
      - "v*.*.*"
    # paths:
    # - src/*
jobs:
    check-links:
      runs-on: ubuntu-latest
      steps:  
      - name: pull repo
        uses: actions/checkout@v1 
        with:
          ref: 'test'
      
      - name: install node
        uses: actions/setup-node@v3
      
      - name: node version
        if: ${{ github.ref == 'refs/heads/pre' && startsWith(github.ref, 'refs/tags/') }}
      - run: echo ${{  secrets.MYSECRETS  }}
      - run: npm version
      - run: echo 111