name: MYCI
on:
  push:
    branches:
    - main
    # tags:
    #   - "v*.*.*"
    # paths:
    # - src/*
jobs:
    check-links:
      runs-on: ubuntu-latest
      steps:  
        - name: checkout
          uses: actions/checkout@v3
          run: |
            ls
      # - uses: actions/checkout@v1 
      # - uses: actions/setup-node@v3
      # - run: echo ${{  secrets.MYSECRETS  }}
      # - run: npm version
      # - run: echo 111
      

