name: MYCI
on:
  push:
    branches:
      - test
    tags:
      - "v*.*.*"
    # paths:
    # - src/*
jobs:
    check-links:
      runs-on: ubuntu-latest
      steps:  
      - name: pull repo
        uses: actions/checkout@v1 
        with:
          ref: 'test'
      
      - name: install node
        uses: actions/setup-node@v3
      
      - name: node version
        if: ${{ startsWith(github.ref, 'refs/tags/') && endsWith(github.ref == 'refs/heads/test') }}
        run: | 
          echo ${{  secrets.MYSECRETS  }}
          npm version
          echo 111