name: MYCI
on:
  push:
    branches:
    - main
    # paths:
    # - src/*
jobs:
    check-links:
      runs-on: ubuntu-latest
      steps:  
      - uses: actions/checkout@v1 
      - uses: actions/setup-node@v3
      - run: echo ${{  secrets.MYSECRETS  }}
      - run: npm version
      - run: echo 111