name: tronlink_prd_ci

on: 
  workflow_dispatch:
  push:
    tags:
      - "v*.*.*"

env:
  AWS_REGION: us-east-1
  AWS_S3_BUCKET: 'tronlink.dlive.org'

permissions: write-all
 
jobs:  
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # - name: upload assets
      #   uses: jakejarvis/s3-sync-action@master
      #   with:
      #     args: --follow-symlinks 
      #   env:
      #     AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET_TRONLINK_PRD }}
      #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_TRONLINK_PRD }}
      #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_TRONLINK_PRD }}
      #     AWS_REGION: 'us-east-1'
      #     SOURCE_DIR: './'

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_STAGING }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_STAGING }}
          aws-region: us-east-1

      - name: backup
        run: |
          echo "IMAGE_TAG=${GITHUB_REF/refs\/tags\//}"
          tar cvzf $IMAGE_TAG.tar.gz ./staging 

      - name: upload backup
        run: |
          aws s3 sync $IMAGE_TAG.tar.gz s3://web-neo-csr-backup 


      - name: upload assets
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --follow-symlinks --delete
        env:
          IMAGE_TAG: ${{ env.IMAGE_TAG }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_STAGING }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_STAGING }}
          AWS_REGION: us-east-1
          AWS_S3_BUCKET: 'web-neo-csr-backup'
          SOURCE_DIR: './${{ env.IMAGE_TAG }}.tar.gz'


# name: MYCI
# on:
#   push:
#     branches:
#     - main
#     # tags:
#     #   - "v*.*.*"
#     # paths:
#     # - src/*
# jobs:
#   TEST:
#     name: test
#     runs-on: ubuntu-latest
#     steps:  
#       - name: checkout
#         uses: actions/checkout@v3

#       - name: ls checkout
#         run: |
#           ls 

#       # - uses: actions/checkout@v1 
#       # - uses: actions/setup-node@v3
#       # - run: echo ${{  secrets.MYSECRETS  }}
#       # - run: npm version
#       # - run: echo 111
      


