name: MYCI
on:
  push:
    branches:
    - main
    # tags:
    #   - "v*.*.*"
    # paths:
    # - src/*
jobs:
  TEST:
    name: test
    runs-on: ubuntu-latest
    steps:  
      - name: checkout
        uses: actions/checkout@v3

      - name: ls checkout
        run: |
          ls
          ls /home/runner/work/
          ls /home/runner/work/ActionDemo/
      # - uses: actions/checkout@v1 
      # - uses: actions/setup-node@v3
      # - run: echo ${{  secrets.MYSECRETS  }}
      # - run: npm version
      # - run: echo 111
      

