name: stg_csr_webneo

on:
  # workflow_dispatch:
  # push:
  #   branches:
  #     - main
  release:
    types: [released]

permissions: write-all

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_STAGING }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_STAGING }}
          aws-region: us-east-1

      - name: backup
        run: |
          # aws s3 sync ./dist s3://web-neo-csr-backup/stg-csr/webcsr-v0.0.1/
          echo "IMAGE_TAG=${GITHUB_REF/refs\/tags\//}"

