name: stg_csr_webneo

on:
  workflow_dispatch:
  push:
    branches:
      - stg


env:
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

permissions: write-all

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_STAGING }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_STAGING }}
          aws-region: us-east-1

      - name: backup
        run: |
          echo "IMAGE_TAG=${GITHUB_REF/refs\/tags\//}"
          IMAGE_TAG=${GITHUB_REF/refs\/tags\//}
          # tar cvzf $IMAGE_TAG.tar.gz ./staging 
          # aws s3 cp $IMAGE_TAG.tar.gz s3://web-neo-csr-backup/webcsr-$IMAGE_TAG/
          # aws s3 sync s3://website.stg.dlive.tv s3://web-neo-csr-backup/webcsr-$IMAGE_TAG/
          aws s3 sync .staging s3://web-neo-csr-backup/webcsr-v0.0.1/
